### ISSUE TITLE
Autoprof Older Version Documentation

### ISSUE THREAD

**Issue by JordanDucatel** [Autostronomy/AutoProf#10]
Hello,

I was using AutoProf a little while ago with version 0.7.3, which had a ReadtheDocs documentation. Due to an updated version of AutoProf being available, the ReadtheDocs was also updated. In ReadtheDocs, only the latest version of the documentation is available, which made the documentation for AutoProf version 0.7.3 unavailable anywhere. Would it be possible to make this older version of the documentation available?

Thank you.

**Comment by ConnorStoneAstro** [comment]
Ah, apologies for the confusion. AutoProf has gone through some naming updates while we were trying to figure out how it fit with previous projects. I believe the "AutoProf" you were using is now called "AstroPhot" which you can find here:
https://github.com/Autostronomy/AstroPhot

However, this still doesn't solve you problem of the docs being for the latest version...  I'll look into making older versions of the docs available, but it seems this is pretty hard to do. In the meantime a workaround is that you can look at the older version of the code here: 
https://github.com/Autostronomy/AstroPhot/tree/7dff8fccc1d8d19ea60a2fa1958276ebdaf29d5a

Browsing the files you can find the old jupyter notebook tutorials here:
https://github.com/Autostronomy/AstroPhot/tree/7dff8fccc1d8d19ea60a2fa1958276ebdaf29d5a/docs/tutorials

And you can find `.rst` versions of the old docs here:
https://github.com/Autostronomy/AstroPhot/tree/7dff8fccc1d8d19ea60a2fa1958276ebdaf29d5a/docs

It's an imperfect solution, but if there is just something specific you are interested in then it should be there.

You may want to update to the latest version though, there are a number of improvements that have been added in now :)

**Comment by JordanDucatel** [comment]
> Ah, apologies for the confusion. AutoProf has gone through some naming updates while we were trying to figure out how it fit with previous projects. I believe the "AutoProf" you were using is now called "AstroPhot" which you can find here: https://github.com/Autostronomy/AstroPhot
> 
> However, this still doesn't solve you problem of the docs being for the latest version... I'll look into making older versions of the docs available, but it seems this is pretty hard to do. In the meantime a workaround is that you can look at the older version of the code here: https://github.com/Autostronomy/AstroPhot/tree/7dff8fccc1d8d19ea60a2fa1958276ebdaf29d5a
> 
> Browsing the files you can find the old jupyter notebook tutorials here: https://github.com/Autostronomy/AstroPhot/tree/7dff8fccc1d8d19ea60a2fa1958276ebdaf29d5a/docs/tutorials
> 
> And you can find `.rst` versions of the old docs here: https://github.com/Autostronomy/AstroPhot/tree/7dff8fccc1d8d19ea60a2fa1958276ebdaf29d5a/docs
> 
> It's an imperfect solution, but if there is just something specific you are interested in then it should be there.
> 
> You may want to update to the latest version though, there are a number of improvements that have been added in now :)

Great! Thank you very much! (And yes you are right, I will probably end up updating to the latest version)
