### ISSUE TITLE
y axis label of the diagnostic plot for finding global PA

### ISSUE THREAD

**Issue by hgao-astro** [Autostronomy/AutoProf#7]
The y label should be FFT_2 phase instead of FFT_1 phase (see below for an example), according to the text in Sect. 2.4 of the AutoProf paper. However, Figure 4 of the AutoProf says it is FFT_1. I believe that it should be FFT2, since FFT1 is mostly useful for finding centers/lopsidedness.
![Screen Shot 2023-03-10 at 4 20 23 PM](https://user-images.githubusercontent.com/8177868/224460049-56e7cee0-5f96-41a3-b5c0-77f30130e508.png)

**Comment by ConnorStoneAstro** [comment]
Whoa, nice catch! I can update that now.

**Comment by hgao-astro** [comment]
Thanks for the quick fix!
